-- 0051_muse_orders.sql
-- Impact OS — orders and menu cycles (Roadmap Phase H3).
--
-- An order is a date, a customer, a site, a channel, a recipe, a meal count and
-- a status. It is what production plans against and what a delivery is
-- recorded against.
--
--   * menu_cycles      — per channel: a repeating sequence of service days that
--                        names which recipe every site on the channel is served
--                        on which date. `start_date` anchors day 1 to the
--                        calendar; `weekdays` are the service days (0 = Sunday …
--                        6 = Saturday) the cycle advances on. A per-site service
--                        calendar (closures, holidays) is not modelled yet.
--   * menu_cycle_days  — one row per cycle day, naming the recipe served.
--   * orders           — the rows the platform stores. Status is
--                        'forecast' | 'confirmed' | 'delivered'.
--
-- A FORECAST ORDER GENERATED BY A MENU CYCLE IS NOT STORED. It is a derived
-- figure — the cycle's recipe on the date × the site's participation forecast —
-- and the engine computes it whenever the order book is read, so a change to a
-- site's forecast or to the cycle moves every forecast order with it and
-- nothing stale sits in a table. A row is written when a count is typed
-- (a forecast order for a retail site, `source = 'typed'`), when a customer
-- confirms the count (`status = 'confirmed'`), and when the meals are
-- delivered (`status = 'delivered'`, `delivery_id` names the delivery record
-- in muse.deliveries, which is what posts revenue). A stored row replaces the
-- derived order with the same date, site and recipe.
--
-- Price on an order is optional: NULL means the customer's contracted price,
-- else the channel default, resolved when read. Meals is a count; every
-- dollar is computed from it.

CREATE SCHEMA IF NOT EXISTS muse;

CREATE TABLE IF NOT EXISTS muse.menu_cycles (
  id           uuid         PRIMARY KEY DEFAULT gen_random_uuid(),
  channel      integer      NOT NULL,
  name         text         NOT NULL,
  start_date   date         NOT NULL,
  -- Service days in one turn of the cycle.
  length_days  integer      NOT NULL DEFAULT 5,
  -- Weekdays the cycle advances on, e.g. [1,2,3,4,5].
  weekdays     jsonb        NOT NULL DEFAULT '[1,2,3,4,5]'::jsonb,
  -- 'active' | 'inactive'
  status       text         NOT NULL DEFAULT 'active',
  notes        text,
  -- 'seed' | 'user_built'
  source       text         NOT NULL DEFAULT 'user_built',
  created_by   text,
  created_at   timestamptz  NOT NULL DEFAULT now(),
  updated_at   timestamptz  NOT NULL DEFAULT now(),
  CONSTRAINT muse_menu_cycles_channel CHECK (channel BETWEEN 1 AND 3),
  CONSTRAINT muse_menu_cycles_length CHECK (length_days BETWEEN 1 AND 60),
  CONSTRAINT muse_menu_cycles_status CHECK (status IN ('active', 'inactive'))
);
CREATE INDEX IF NOT EXISTS muse_menu_cycles_channel_idx ON muse.menu_cycles (channel);

CREATE TABLE IF NOT EXISTS muse.menu_cycle_days (
  id           uuid         PRIMARY KEY DEFAULT gen_random_uuid(),
  cycle_id     uuid         NOT NULL REFERENCES muse.menu_cycles (id) ON DELETE CASCADE,
  -- 1 .. length_days
  day          integer      NOT NULL,
  -- The library recipe served that day; NULL = no service (a day off the menu).
  recipe_code  text,
  created_at   timestamptz  NOT NULL DEFAULT now(),
  CONSTRAINT muse_menu_cycle_days_day CHECK (day >= 1),
  CONSTRAINT muse_menu_cycle_days_unique UNIQUE (cycle_id, day)
);
CREATE INDEX IF NOT EXISTS muse_menu_cycle_days_cycle_idx ON muse.menu_cycle_days (cycle_id, day);

CREATE TABLE IF NOT EXISTS muse.orders (
  id                   uuid         PRIMARY KEY DEFAULT gen_random_uuid(),
  order_date           date         NOT NULL,
  customer_id          uuid         NOT NULL REFERENCES muse.customers (id) ON DELETE CASCADE,
  customer_site_id     uuid         NOT NULL REFERENCES muse.customer_sites (id) ON DELETE CASCADE,
  channel              integer      NOT NULL,
  recipe_code          text         NOT NULL,
  meals                double precision NOT NULL,
  -- 'forecast' | 'confirmed' | 'delivered'
  status               text         NOT NULL DEFAULT 'forecast',
  -- NULL = the customer's contracted price, else the channel default.
  price_per_meal_cents integer,
  -- The delivery record, once delivered. Removing the record leaves the order.
  delivery_id          uuid         REFERENCES muse.deliveries (id) ON DELETE SET NULL,
  -- The cycle the order was confirmed from, when it was.
  menu_cycle_id        uuid         REFERENCES muse.menu_cycles (id) ON DELETE SET NULL,
  -- 'typed' | 'cycle' | 'sales' | 'portal'
  source               text         NOT NULL DEFAULT 'typed',
  notes                text,
  created_by           text,
  created_at           timestamptz  NOT NULL DEFAULT now(),
  updated_at           timestamptz  NOT NULL DEFAULT now(),
  CONSTRAINT muse_orders_channel CHECK (channel BETWEEN 1 AND 3),
  CONSTRAINT muse_orders_meals_nonneg CHECK (meals >= 0),
  CONSTRAINT muse_orders_status CHECK (status IN ('forecast', 'confirmed', 'delivered')),
  CONSTRAINT muse_orders_source CHECK (source IN ('typed', 'cycle', 'sales', 'portal')),
  -- One stored order per date, site and recipe: it is the row that replaces the derived one.
  CONSTRAINT muse_orders_unique_line UNIQUE (order_date, customer_site_id, recipe_code)
);
CREATE INDEX IF NOT EXISTS muse_orders_date_idx ON muse.orders (order_date);
CREATE INDEX IF NOT EXISTS muse_orders_customer_idx ON muse.orders (customer_id, order_date);
CREATE INDEX IF NOT EXISTS muse_orders_site_idx ON muse.orders (customer_site_id);
CREATE INDEX IF NOT EXISTS muse_orders_delivery_idx ON muse.orders (delivery_id);
