-- 0079_muse_equipment_spec_sheets.sql
-- Impact OS — footprints re-sourced to spec sheets; manufacturer, model and spec sheet on the row.
--
-- Every row with floor now reads its width, depth and published clearances off
-- a named representative model's spec sheet (facility-design roadmap §5,
-- re-sourced 2026-09-17), and carries the manufacturer, the model and the
-- sheet's link. The three columns are shown on the Facility page's Footprints
-- tab, not on Equipment. Rows an admin has stated or measured are left alone.
-- Data plus three nullable columns; idempotent.

ALTER TABLE muse.equipment ADD COLUMN IF NOT EXISTS manufacturer text;
ALTER TABLE muse.equipment ADD COLUMN IF NOT EXISTS model text;
ALTER TABLE muse.equipment ADD COLUMN IF NOT EXISTS spec_sheet_url text;

UPDATE muse.equipment SET footprint_width_in = 42.625, footprint_depth_in = 44, clearance_front_in = NULL, clearance_rear_in = NULL, clearance_side_in = NULL, footprint_basis = 'sourced', footprint_source = 'Rational iCombi Pro 20-full, 42-5/8 x 44 in total', manufacturer = 'Rational', model = 'iCombi Pro 20-full', spec_sheet_url = 'https://www.webstaurantstore.com/documents/specsheets/pro_20-full.pdf'
  WHERE source = 'seed' AND footprint_basis IN ('estimated', 'sourced') AND item = 'Combi oven, full size 20-pan';
UPDATE muse.equipment SET footprint_width_in = 51, footprint_depth_in = 44, clearance_front_in = NULL, clearance_rear_in = NULL, clearance_side_in = NULL, footprint_basis = 'sourced', footprint_source = 'Cleveland KEL-100-T, 51 x 44 in', manufacturer = 'Cleveland', model = 'KEL-100-T', spec_sheet_url = 'https://www.clevelandrange.com/product/kel100t-electric-steam-kettles-quad-leg-tilting/'
  WHERE source = 'seed' AND footprint_basis IN ('estimated', 'sourced') AND item = 'Steam-jacketed tilting kettle, 100 gal';
UPDATE muse.equipment SET footprint_width_in = 48, footprint_depth_in = 44, clearance_front_in = NULL, clearance_rear_in = NULL, clearance_side_in = NULL, footprint_basis = 'sourced', footprint_source = 'Cleveland SGL-40-TR, 48 x 44 in', manufacturer = 'Cleveland', model = 'SGL-40-TR', spec_sheet_url = 'https://www.clevelandrange.com/wp-content/uploads/2025/02/KE004046-93-SGL-30-40TR.pdf'
  WHERE source = 'seed' AND footprint_basis IN ('estimated', 'sourced') AND item = 'Tilting braising pan / skillet, 40 gal';
UPDATE muse.equipment SET footprint_width_in = 40.25, footprint_depth_in = 41.125, clearance_front_in = NULL, clearance_rear_in = NULL, clearance_side_in = NULL, footprint_basis = 'sourced', footprint_source = 'Vulcan VC44ED, 40-1/4 x 41-1/8 in', manufacturer = 'Vulcan', model = 'VC44ED', spec_sheet_url = 'https://www.vulcanequipment.com/sites/default/files/webdam_asset/85620879.pdf'
  WHERE source = 'seed' AND footprint_basis IN ('estimated', 'sourced') AND item = 'Convection oven, double stack';
UPDATE muse.equipment SET footprint_width_in = 49.375, footprint_depth_in = 47.25, clearance_front_in = NULL, clearance_rear_in = NULL, clearance_side_in = NULL, footprint_basis = 'sourced', footprint_source = 'Cleveland KGL-60-T, 49-3/8 x 47-1/4 in', manufacturer = 'Cleveland', model = 'KGL-60-T', spec_sheet_url = 'https://www.clevelandrange.com/wp-content/uploads/2025/02/KE004046-73-KGL-40-60-80-T.pdf'
  WHERE source = 'seed' AND footprint_basis IN ('estimated', 'sourced') AND item = 'Steam-jacketed tilting kettle, 60 gal';
UPDATE muse.equipment SET footprint_width_in = 94, footprint_depth_in = 27, clearance_front_in = NULL, clearance_rear_in = NULL, clearance_side_in = NULL, footprint_basis = 'sourced', footprint_source = 'Advance Tabco 94-3-54-24RL (103 x 27 in) and 94-2-36-24RL (85 x 27 in), one of each, averaged to 94 x 27 in', manufacturer = 'Advance Tabco', model = '94-3-54-24RL / 94-2-36-24RL', spec_sheet_url = 'https://www.webstaurantstore.com/advance-tabco-94-3-54-24rl-spec-line-three-compartment-pot-sink-with-two-drainboards-103/1099435424B.html'
  WHERE source = 'seed' AND footprint_basis IN ('estimated', 'sourced') AND item = 'Prep sinks, 3-comp and 2-comp';
UPDATE muse.equipment SET footprint_width_in = 96, footprint_depth_in = 30, clearance_front_in = NULL, clearance_rear_in = NULL, clearance_side_in = NULL, footprint_basis = 'sourced', footprint_source = 'Advance Tabco TTS-308, 96 x 30 in', manufacturer = 'Advance Tabco', model = 'TTS-308', spec_sheet_url = 'https://www.gofoodservice.com/p/advance-tabco-tts-308'
  WHERE source = 'seed' AND footprint_basis IN ('estimated', 'sourced') AND item = 'Stainless prep tables, 8 ft';
UPDATE muse.equipment SET footprint_width_in = 36.125, footprint_depth_in = 34, clearance_front_in = NULL, clearance_rear_in = NULL, clearance_side_in = NULL, footprint_basis = 'sourced', footprint_source = 'Hobart HCM450, 36-1/8 x 34 in', manufacturer = 'Hobart', model = 'HCM450', spec_sheet_url = 'https://www.hobartcorp.com/sites/default/files/webdam-assets/HCM450%20Cutter%20Mixer%20Spec%20Sheet%20F7734%20(04-23).pdf'
  WHERE source = 'seed' AND footprint_basis IN ('estimated', 'sourced') AND item = 'Vertical cutter mixer, 45 qt';
UPDATE muse.equipment SET footprint_width_in = 27.25, footprint_depth_in = 46, clearance_front_in = 14.1875, clearance_rear_in = NULL, clearance_side_in = NULL, footprint_basis = 'sourced', footprint_source = 'Hobart HL800, 27-1/4 x 46 in; the bowl swings out to 60-3/16 in, carried as 14-3/16 in front clearance', manufacturer = 'Hobart', model = 'HL800', spec_sheet_url = 'https://www.hobartcorp.com/sites/default/files/webdam-assets/HL800%20Legacy%20PLUS%20Spec%20Sheet%20F40113%20(07-21).pdf'
  WHERE source = 'seed' AND footprint_basis IN ('estimated', 'sourced') AND item = 'Planetary mixer, 80 qt';
UPDATE muse.equipment SET footprint_width_in = 41, footprint_depth_in = 35, clearance_front_in = NULL, clearance_rear_in = NULL, clearance_side_in = NULL, footprint_basis = 'sourced', footprint_source = 'Traulsen TBC13 (supersedes RBC200), 41 x 35 in, 200 lb rated', manufacturer = 'Traulsen', model = 'TBC13', spec_sheet_url = 'https://www.hobart.ca/wp-content/uploads/2024/03/TBC13-Blast-Chiller-Reach-In-Spec-Sheet-TR36053-10-23.pdf'
  WHERE source = 'seed' AND footprint_basis IN ('estimated', 'sourced') AND item = 'Blast chiller, 200 lb capacity';
UPDATE muse.equipment SET footprint_width_in = 62, footprint_depth_in = 35.5, clearance_front_in = NULL, clearance_rear_in = NULL, clearance_side_in = NULL, footprint_basis = 'sourced', footprint_source = 'Cres Cor R-171-SUA-20E ChillTemp two-door mobile refrigerated cabinet, 62 x 35-1/2 in', manufacturer = 'Cres Cor', model = 'R-171-SUA-20E', spec_sheet_url = 'https://www.crescor.com/product/r171sua20e/'
  WHERE source = 'seed' AND footprint_basis IN ('estimated', 'sourced') AND item = 'Casing handling, chill carts';
UPDATE muse.equipment SET footprint_width_in = 48, footprint_depth_in = 22, clearance_front_in = NULL, clearance_rear_in = NULL, clearance_side_in = NULL, footprint_basis = 'sourced', footprint_source = 'Cleveland MFS Metering Filling Station, 48 x 22 in', manufacturer = 'Cleveland', model = 'MFS', spec_sheet_url = 'https://www.clevelandrange.com/product/fam_lfgsem/mfs-metering-filling-station/'
  WHERE source = 'seed' AND footprint_basis IN ('estimated', 'sourced') AND item = 'Cook-chill pump fill station';
UPDATE muse.equipment SET footprint_width_in = 98, footprint_depth_in = 93, clearance_front_in = 60, clearance_rear_in = 24, clearance_side_in = 24, footprint_basis = 'sourced', footprint_source = 'Cleveland P-TC-220 vertical tumble chiller, 98 x 93 in. Published clearances 60 in front, 24 in rear, 12 in one side and 36 in the electrical side (carried as 24 in each side)', manufacturer = 'Cleveland', model = 'P-TC-220', spec_sheet_url = 'https://www.clevelandrange.com/wp-content/uploads/2026/06/Tumble_Chiller.pdf'
  WHERE source = 'seed' AND footprint_basis IN ('estimated', 'sourced') AND item = 'Tumble chiller / ice water bath system';
UPDATE muse.equipment SET footprint_width_in = 96, footprint_depth_in = 30, clearance_front_in = NULL, clearance_rear_in = NULL, clearance_side_in = NULL, footprint_basis = 'sourced', footprint_source = 'Advance Tabco TTS-308, 96 x 30 in', manufacturer = 'Advance Tabco', model = 'TTS-308', spec_sheet_url = 'https://www.gofoodservice.com/p/advance-tabco-tts-308'
  WHERE source = 'seed' AND footprint_basis IN ('estimated', 'sourced') AND item = 'Packaging tables, stainless';
UPDATE muse.equipment SET footprint_width_in = 50.39, footprint_depth_in = 42.83, clearance_front_in = NULL, clearance_rear_in = NULL, clearance_side_in = NULL, footprint_basis = 'sourced', footprint_source = 'Ilpra FoodPack Synergy, 1280 x 1088 mm', manufacturer = 'Ilpra', model = 'FoodPack Synergy', spec_sheet_url = 'https://ilpra.com/packaging_machine/foodpack-synergy/'
  WHERE source = 'seed' AND footprint_basis IN ('estimated', 'sourced') AND item = 'Tray sealer, semi-automatic';
UPDATE muse.equipment SET footprint_width_in = 75, footprint_depth_in = 41, clearance_front_in = NULL, clearance_rear_in = NULL, clearance_side_in = NULL, footprint_basis = 'sourced', footprint_source = 'VacMaster VP800 double chamber, 75 x 41 in', manufacturer = 'VacMaster', model = 'VP800', spec_sheet_url = 'https://alfaco.com/product/vacmaster-vp800-double-chamber-vacuum-sealer/'
  WHERE source = 'seed' AND footprint_basis IN ('estimated', 'sourced') AND item = 'Vacuum packaging machine, chamber';
UPDATE muse.equipment SET footprint_width_in = 28.3125, footprint_depth_in = 37.375, clearance_front_in = NULL, clearance_rear_in = NULL, clearance_side_in = NULL, footprint_basis = 'sourced', footprint_source = 'Cres Cor R-171-SUA-10E ChillTemp single-door mobile refrigerated cabinet, 28-5/16 x 37-3/8 in', manufacturer = 'Cres Cor', model = 'R-171-SUA-10E', spec_sheet_url = 'https://www.katom.com/546-R171SUA10E.html'
  WHERE source = 'seed' AND footprint_basis IN ('estimated', 'sourced') AND item = 'Mobile refrigerated holding cabinet';
UPDATE muse.equipment SET footprint_width_in = 54.125, footprint_depth_in = 29.5, clearance_front_in = NULL, clearance_rear_in = NULL, clearance_side_in = NULL, footprint_basis = 'sourced', footprint_source = 'True T-49-HC two-section reach-in, 54-1/8 x 29-1/2 in', manufacturer = 'True', model = 'T-49-HC', spec_sheet_url = 'https://www.truemfg.com/product/t-49-hc/'
  WHERE source = 'seed' AND footprint_basis IN ('estimated', 'sourced') AND item = 'Reach-in refrigerator, 2-door';
UPDATE muse.equipment SET footprint_width_in = 144, footprint_depth_in = 240, clearance_front_in = NULL, clearance_rear_in = NULL, clearance_side_in = NULL, footprint_basis = 'sourced', footprint_source = 'Nominal 12 x 20 ft from the item name; door on the 12 ft wall', manufacturer = NULL, model = NULL, spec_sheet_url = NULL
  WHERE source = 'seed' AND footprint_basis IN ('estimated', 'sourced') AND item = 'Walk-in cooler, 12x20, with refrigeration';
UPDATE muse.equipment SET footprint_width_in = 120, footprint_depth_in = 144, clearance_front_in = NULL, clearance_rear_in = NULL, clearance_side_in = NULL, footprint_basis = 'sourced', footprint_source = 'Nominal 10 x 12 ft from the item name; door on the 10 ft wall', manufacturer = NULL, model = NULL, spec_sheet_url = NULL
  WHERE source = 'seed' AND footprint_basis IN ('estimated', 'sourced') AND item = 'Walk-in freezer, 10x12, with refrigeration';
UPDATE muse.equipment SET footprint_width_in = 120, footprint_depth_in = 144, clearance_front_in = NULL, clearance_rear_in = NULL, clearance_side_in = NULL, footprint_basis = 'sourced', footprint_source = 'Nominal 10 x 12 ft from the item name; door on the 10 ft wall', manufacturer = NULL, model = NULL, spec_sheet_url = NULL
  WHERE source = 'seed' AND footprint_basis IN ('estimated', 'sourced') AND item = 'Walk-in cooler, 10x12, with refrigeration';
UPDATE muse.equipment SET footprint_width_in = 96, footprint_depth_in = 120, clearance_front_in = NULL, clearance_rear_in = NULL, clearance_side_in = NULL, footprint_basis = 'sourced', footprint_source = 'Nominal 8 x 10 ft from the item name; door on the 8 ft wall', manufacturer = NULL, model = NULL, spec_sheet_url = NULL
  WHERE source = 'seed' AND footprint_basis IN ('estimated', 'sourced') AND item = 'Walk-in freezer, 8x10, with refrigeration';
UPDATE muse.equipment SET footprint_width_in = 17.25, footprint_depth_in = 15.25, clearance_front_in = NULL, clearance_rear_in = NULL, clearance_side_in = NULL, footprint_basis = 'sourced', footprint_source = 'Lot of 6: five Advance Tabco 7-PS-60 wall-hung hand sinks, 17-1/4 x 15-1/4 in each (the unit carried), and one 9-OP-40 floor mop sink, 25 x 21 in', manufacturer = 'Advance Tabco', model = '7-PS-60 / 9-OP-40', spec_sheet_url = 'https://www.webstaurantstore.com/advance-tabco-7-ps-60-hand-sink-with-splash-mount-faucet-17-1-4-x-15-1-4/1097PS60.html'
  WHERE source = 'seed' AND footprint_basis IN ('estimated', 'sourced') AND item = 'Hand sinks and mop sink';
UPDATE muse.equipment SET footprint_width_in = 127, footprint_depth_in = 31, clearance_front_in = NULL, clearance_rear_in = NULL, clearance_side_in = NULL, footprint_basis = 'sourced', footprint_source = 'Advance Tabco 94-43-72-24RL, three 24 x 24 in compartments and two 24 in drainboards, 127 x 31 in', manufacturer = 'Advance Tabco', model = '94-43-72-24RL', spec_sheet_url = 'https://www.webstaurantstore.com/advance-tabco-94-43-72-24rl-spec-line-three-compartment-pot-sink-with-two-drainboards-127/10994437224B.html'
  WHERE source = 'seed' AND footprint_basis IN ('estimated', 'sourced') AND item = 'Pot sink, 3-comp with drainboards';
UPDATE muse.equipment SET footprint_width_in = 84, footprint_depth_in = 26.6875, clearance_front_in = NULL, clearance_rear_in = NULL, clearance_side_in = NULL, footprint_basis = 'sourced', footprint_source = 'Champion 80 PRO-HD, 84 x 26-11/16 in', manufacturer = 'Champion', model = '80 PRO-HD', spec_sheet_url = 'https://www.championindustries.com/80-PRO-Heavy-Duty-Prewash-Rack-Conveyor'
  WHERE source = 'seed' AND footprint_basis IN ('estimated', 'sourced') AND item = 'Rack conveyor dishwasher + booster';
UPDATE muse.equipment SET footprint_width_in = 48.25, footprint_depth_in = 22, clearance_front_in = NULL, clearance_rear_in = NULL, clearance_side_in = NULL, footprint_basis = 'sourced', footprint_source = 'Rubbermaid FG9T7200 high-capacity janitor cart, 48-1/4 x 22 in', manufacturer = 'Rubbermaid Commercial', model = 'FG9T7200', spec_sheet_url = 'https://www.katom.com/007-FG9T7200BLA.html'
  WHERE source = 'seed' AND footprint_basis IN ('estimated', 'sourced') AND item = 'Sanitation cart, chemical dispensing';
UPDATE muse.equipment SET footprint_width_in = 18, footprint_depth_in = 25, clearance_front_in = NULL, clearance_rear_in = NULL, clearance_side_in = NULL, footprint_basis = 'sourced', footprint_source = 'Cambro UPC400 Ultra Pan Carrier, front loading, 18 x 25 in', manufacturer = 'Cambro', model = 'UPC400', spec_sheet_url = 'https://www.webstaurantstore.com/cambro-upc400110-ultra-pan-carrier-black-front-loading-insulated-food-pan-carrier/214UPC400BK.html'
  WHERE source = 'seed' AND footprint_basis IN ('estimated', 'sourced') AND item = 'Insulated transport carts';
UPDATE muse.equipment SET footprint_width_in = 28.75, footprint_depth_in = 32.75, clearance_front_in = NULL, clearance_rear_in = NULL, clearance_side_in = NULL, footprint_basis = 'sourced', footprint_source = 'Cres Cor H-137-UA-12D insulated holding cabinet, 28-3/4 x 32-3/4 in', manufacturer = 'Cres Cor', model = 'H-137-UA-12D', spec_sheet_url = 'https://www.webstaurantstore.com/cres-cor-h-137-ua-12d-insulated-holding-cabinet-solid-dutch-doors-120v/265H137UA12D.html'
  WHERE source = 'seed' AND footprint_basis IN ('estimated', 'sourced') AND item = 'Hot holding cabinets, insulated';
UPDATE muse.equipment SET footprint_width_in = 31.25, footprint_depth_in = 34.375, clearance_front_in = NULL, clearance_rear_in = NULL, clearance_side_in = NULL, footprint_basis = 'sourced', footprint_source = 'Pitco SG14-2FD Solstice two-vat floor fryer with filter drawer, 31-1/4 x 34-3/8 in', manufacturer = 'Pitco', model = 'SG14-2FD', spec_sheet_url = 'https://www.pitco.com/wp-content/uploads/2022/02/L10-294-R2-SG14-with-Options.pdf'
  WHERE source = 'seed' AND footprint_basis IN ('estimated', 'sourced') AND item = 'Fry station, double vat';
UPDATE muse.equipment SET footprint_width_in = 36, footprint_depth_in = 31.5, clearance_front_in = NULL, clearance_rear_in = NULL, clearance_side_in = NULL, footprint_basis = 'sourced', footprint_source = 'Vulcan MSA36 heavy-duty countertop griddle on an equipment stand, 36 x 31-1/2 in', manufacturer = 'Vulcan', model = 'MSA36', spec_sheet_url = 'https://www.vulcanequipment.com/griddles/36-msa-series-flat-top-gas-griddle'
  WHERE source = 'seed' AND footprint_basis IN ('estimated', 'sourced') AND item = 'Griddle / plancha, 36 in';
UPDATE muse.equipment SET footprint_width_in = 36, footprint_depth_in = 27.25, clearance_front_in = NULL, clearance_rear_in = NULL, clearance_side_in = NULL, footprint_basis = 'sourced', footprint_source = 'Vulcan VCCB36 radiant charbroiler on a stand, 36 x 27-1/4 in; salamander wall-mounted above', manufacturer = 'Vulcan', model = 'VCCB36', spec_sheet_url = 'https://www.katom.com/207-VCCB36NG.html'
  WHERE source = 'seed' AND footprint_basis IN ('estimated', 'sourced') AND item = 'Charbroiler and salamander';
UPDATE muse.equipment SET footprint_width_in = 48.375, footprint_depth_in = 31.125, clearance_front_in = NULL, clearance_rear_in = NULL, clearance_side_in = NULL, footprint_basis = 'sourced', footprint_source = 'True TWT-48-HC two-section worktop refrigerator, 48-3/8 x 31-1/8 in', manufacturer = 'True', model = 'TWT-48-HC', spec_sheet_url = 'https://www.truemfg.com/wp-content/uploads/true-media/spec-sheets/TWT-48-HC.pdf'
  WHERE source = 'seed' AND footprint_basis IN ('estimated', 'sourced') AND item = 'A la carte line refrigeration units';
UPDATE muse.equipment SET footprint_width_in = 60, footprint_depth_in = 19.5, clearance_front_in = NULL, clearance_rear_in = NULL, clearance_side_in = NULL, footprint_basis = 'sourced', footprint_source = 'Hatco GRS-60-I Glo-Ray free-standing heated shelf, 60 x 19-1/2 in', manufacturer = 'Hatco', model = 'GRS-60-I', spec_sheet_url = 'https://www.hatcocorp.com/cms/SPECSHEETS/000000004171201-00014-20161121.PDF'
  WHERE source = 'seed' AND footprint_basis IN ('estimated', 'sourced') AND item = 'Heated expo and pickup shelving';
