/**
 * Cotyledon — sources registry seed.
 *
 * Registers, idempotently:
 *   1. Stored documents from the git-ignored research folder (large files that
 *      cannot pass the in-app upload ceiling): the Poore & Nemecek Data S2
 *      workbook and the Quantis White Oak Pastures LCA deck. Matched by SHA-256.
 *   2. One URL-only source per distinct publisher URL in the factor library,
 *      with every factor as a figure keyed by its provenance id. Matched by URL
 *      and provenance id. Re-running updates version/status/note on figures.
 *   3. The reference register (`_data/sources-registry.ts`): every code, rule,
 *      dataset, rate schedule, study and guidance the platform cites outside the
 *      factor library. Matched by URL, else by title.
 *   4. The manufacturer spec sheets the equipment footprints are read from.
 *   5. Retires the URL-only rows an earlier run registered that the code no longer
 *      names (a factor, a reference or a spec sheet removed since): their figures go
 *      with them. A stored document, an upload, or a row some record links to (a
 *      reading, a bill, a service ticket, a supplier price or figure) is never retired;
 *      a linked stale row is reported instead.
 *
 * Run:  FARM_WORKSPACE=org_local_dev pnpm farm:sources
 */

import { createHash } from 'node:crypto';
import { readFile, stat } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { config as loadEnv } from 'dotenv';
import { eq, sql } from 'drizzle-orm';
import { farmSources, farmSourceFigures } from '@/db';
import { scopedHandle } from './_workspace';
import { factorRegistry } from '@/data/emission-factors';
import { groupFactorsBySource, inferMime, specSheetSources } from '@/engine/sources';
import { REFERENCE_SOURCES } from '@/data/sources-registry';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = join(HERE, '..');
loadEnv({ path: join(REPO, '.env') });
loadEnv({ path: join(REPO, '.env.local') });

const RESEARCH = join(REPO, 'docs/farm/confidential/Research');

interface StoredDoc {
  file: string;
  kind: 'study' | 'lca' | 'dataset';
  title: string;
  authors: string;
  publisher: string;
  year: number;
  citation: string;
  sourceUrl: string | null;
  licenceNote: string;
  notes: string;
  /** Provenance ids whose figures should point at this stored document rather than a URL-only source. */
  claims: string[];
  figures: { provenanceId?: string; label: string; valueText: string; unit: string; locator: string; status: string; note?: string }[];
}

const STORED: StoredDoc[] = [
  {
    file: 'Poore_Namecek_Food_Supply_LCA.xlsx',
    kind: 'study',
    title: 'Life Cycle Assessment of Food & Drink Products: Meta-Analysis Model (Data S2)',
    authors: 'Joseph Poore, Thomas Nemecek',
    publisher: 'Science (AAAS), supplementary data',
    year: 2018,
    citation: 'Poore & Nemecek (2018), Reducing food\'s environmental impacts through producers and consumers, Science 360(6392), 987–992',
    sourceUrl: 'https://doi.org/10.1126/science.aaq0216',
    licenceNote: 'Supplementary data to a published article; held for internal reference. Per-product means are derived arithmetic, not a republication.',
    notes: 'Database sheet: 2,734 observation rows, final Weight column sums to 1 per product. Per-product means generated by pnpm farm:input-factors.',
    claims: ['poore-nemecek-2018:data-s2'],
    figures: [],
  },
  {
    file: 'WOP-LCA-Quantis-2019.pdf',
    kind: 'lca',
    title: 'Carbon Footprint Evaluation of Regenerative Grazing at White Oak Pastures',
    authors: 'Mariko Thorbecke, Jon Dettling (Quantis)',
    publisher: 'Quantis, prepared for General Mills / EPIC',
    year: 2019,
    citation: 'Quantis, results presentation, 25 February 2019',
    sourceUrl: null,
    licenceNote: 'Publicly circulated results deck; held for internal reference.',
    notes: 'Carbon only; farm boundary field to slaughter, year 2017; economic allocation of sequestration; not ISO-compliant and not peer-reviewed at the time (slide 32).',
    claims: [],
    figures: [
      { provenanceId: 'quantis-wop-2019:beef-net', label: 'Net footprint of White Oak Pastures beef', valueText: '-3.5', unit: 'kg CO2e per kg fresh meat', locator: 'slides 6, 17, 19', status: 'SOURCED', note: 'Enteric 29, manure 5, other farm 1, slaughter and transport 0.2, soil carbon −35, vegetation carbon −4.' },
      { provenanceId: 'quantis-wop-2019:beef-conventional-rotz', label: 'Conventional US beef comparator (Rotz 2013 basis)', valueText: '33', unit: 'kg CO2e per kg fresh meat', locator: 'slides 6, 19', status: 'SOURCED' },
      { label: 'Difference from conventional US beef', valueText: '111', unit: '% lower', locator: 'slides 5, 22', status: 'SOURCED' },
      { label: 'Share of whole-farm emissions offset by sequestration', valueText: '~85', unit: '%', locator: 'slide 16', status: 'SOURCED' },
      { label: 'Carcass-weight intensity, WOP vs North American average', valueText: '3 vs 16', unit: 'kg CO2e per kg carcass weight', locator: 'slides 7, 21', status: 'SOURCED', note: 'Comparator from Gerber et al. 2013.' },
      { label: 'Methane GWP used', valueText: '30.5', unit: '100-year', locator: 'slide 23', status: 'SOURCED' },
    ],
  },
  {
    file: 'MSU-UCS Study Master.pdf',
    kind: 'study',
    title: 'Impacts of soil carbon sequestration on life cycle greenhouse gas emissions in Midwestern USA beef finishing systems',
    authors: 'Paige L. Stanley, Jason E. Rowntree, David K. Beede, Marcia S. DeLonge, Michael W. Hamm',
    publisher: 'Agricultural Systems (Elsevier); Michigan State University / Union of Concerned Scientists',
    year: 2018,
    citation: 'Agricultural Systems 162 (2018), 249–258',
    sourceUrl: 'https://doi.org/10.1016/j.agsy.2018.02.003',
    licenceNote: 'Open access under CC BY 4.0.',
    notes: 'Comparative LCA of adaptive multi-paddock (AMP) grazing and feedlot finishing, Upper Midwest; finishing phase only; five years of on-farm data and four years of soil carbon data. Beef only.',
    claims: [],
    figures: [
      { provenanceId: 'msu-ucs-amp-2018:beef-net', label: 'AMP grazing finishing, net with soil carbon flux', valueText: '-6.65', unit: 'kg CO2e per kg carcass weight', locator: 'abstract; §3.5; Fig. 2', status: 'SOURCED', note: 'Shown in the basis selector per kg retail mass (÷ 0.68) at the farm gate, finishing phase only.' },
      { label: 'AMP grazing finishing, before soil carbon flux', valueText: '9.62', unit: 'kg CO2e per kg carcass weight', locator: '§3.5; Fig. 2', status: 'SOURCED' },
      { label: 'Feedlot finishing, before soil erosion', valueText: '6.09', unit: 'kg CO2e per kg carcass weight', locator: 'abstract; Fig. 2', status: 'SOURCED' },
      { label: 'Feedlot finishing, net with soil erosion', valueText: '6.12', unit: 'kg CO2e per kg carcass weight', locator: 'abstract; §3.5; Fig. 2', status: 'SOURCED' },
      { label: 'Soil organic carbon sequestration, AMP grazed pastures, 4-year rate', valueText: '3.59', unit: 'Mg C per hectare per year (SE 0.84)', locator: 'Table 4', status: 'SOURCED' },
      { label: 'Net soil carbon credit, AMP, after excluding hay land', valueText: '-16.27', unit: 'kg CO2e per kg carcass weight', locator: '§3.5', status: 'SOURCED' },
      { label: 'Land: feedlot relative to AMP grazing', valueText: 'less than half', unit: 'agricultural land per kg beef', locator: '§4.2', status: 'SOURCED' },
      { label: 'Methane sensitivity: on-farm SF6 data instead of IPCC default', valueText: '-1.81', unit: 'kg CO2e per kg carcass weight (19% of the AMP footprint)', locator: '§3.6; Fig. 3', status: 'SOURCED' },
    ],
  },
];

/** Local files whose registry rows are removed because a better source replaced them. */
const SUPERSEDED: string[] = ['msu_ucs_amp_grazing_metrics.csv'];

async function main(): Promise<void> {
  const handle = await scopedHandle();
  const db = handle.db;
  let sources = 0;
  let figures = 0;

  // 0. Superseded local files: remove their registry rows (figures cascade).
  for (const name of SUPERSEDED) {
    const path = join(RESEARCH, name);
    try {
      const bytes = await readFile(path);
      const sha = createHash('sha256').update(bytes).digest('hex');
      const gone = await db.delete(farmSources).where(eq(farmSources.sha256, sha)).returning({ id: farmSources.id });
      if (gone.length) console.log(`  drop  ${name} (superseded)`);
    } catch {
      /* file not present locally; nothing to drop */
    }
  }

  // 1. Stored documents.
  const claimed = new Map<string, string>(); // provenance id → source id
  for (const doc of STORED) {
    const path = join(RESEARCH, doc.file);
    try {
      await stat(path);
    } catch {
      console.log(`  skip  ${doc.file} (not found locally)`);
      continue;
    }
    const bytes = await readFile(path);
    const sha256 = createHash('sha256').update(bytes).digest('hex');
    const mime = inferMime(doc.file) ?? 'application/octet-stream';
    const existing = await db.select({ id: farmSources.id }).from(farmSources).where(eq(farmSources.sha256, sha256)).limit(1);
    let id: string;
    if (existing[0]) {
      id = existing[0].id;
      await db
        .update(farmSources)
        .set({ kind: doc.kind, title: doc.title, authors: doc.authors, publisher: doc.publisher, year: doc.year, citation: doc.citation, sourceUrl: doc.sourceUrl, licenceNote: doc.licenceNote, notes: doc.notes, updatedAt: new Date() })
        .where(eq(farmSources.id, id));
      console.log(`  ok    ${doc.file} (already stored, metadata refreshed)`);
    } else {
      const ins = await db
        .insert(farmSources)
        .values({
          kind: doc.kind,
          title: doc.title,
          authors: doc.authors,
          publisher: doc.publisher,
          year: doc.year,
          citation: doc.citation,
          sourceUrl: doc.sourceUrl,
          licenceNote: doc.licenceNote,
          status: 'SOURCED',
          notes: doc.notes,
          fileName: doc.file,
          fileMime: mime,
          fileSize: bytes.byteLength,
          sha256,
          fileBytes: bytes,
          uploadedBy: 'seed:farm-sources',
          uploadedAt: new Date(),
        })
        .returning({ id: farmSources.id });
      id = ins[0].id;
      sources++;
      console.log(`  add   ${doc.file} (${(bytes.byteLength / 1048576).toFixed(1)} MB)`);
    }
    for (const c of doc.claims) claimed.set(c, id);
    for (const f of doc.figures) {
      const key = `${id}:${f.label}`;
      const found = f.provenanceId
        ? await db.select({ id: farmSourceFigures.id }).from(farmSourceFigures).where(eq(farmSourceFigures.provenanceId, f.provenanceId)).limit(1)
        : await db
            .select({ id: farmSourceFigures.id })
            .from(farmSourceFigures)
            .where(sql`${farmSourceFigures.sourceId} = ${id} and ${farmSourceFigures.label} = ${f.label}`)
            .limit(1);
      if (found[0]) {
        await db.update(farmSourceFigures).set({ sourceId: id, provenanceId: f.provenanceId ?? null, label: f.label, valueText: f.valueText, unit: f.unit, locator: f.locator, status: f.status, note: f.note ?? null }).where(eq(farmSourceFigures.id, found[0].id));
      } else {
        await db.insert(farmSourceFigures).values({ sourceId: id, provenanceId: f.provenanceId ?? null, label: f.label, valueText: f.valueText, unit: f.unit, locator: f.locator, status: f.status, note: f.note ?? null });
        figures++;
      }
      void key;
    }
  }

  // Everything the code names: the retirement step keeps these and drops the rest of the seed's URL-only rows.
  const namedUrls = new Set<string>();
  const namedTitles = new Set<string>();

  // 2. URL-only sources from the factor library, one per publisher URL.
  for (const g of groupFactorsBySource(factorRegistry)) {
    namedUrls.add(g.sourceUrl);
    // Figures whose provenance id is claimed by a stored document attach there instead.
    const stored = g.figures.filter((f) => claimed.has(f.id) || claimed.has(f.id.split(':').slice(0, 2).join(':')));
    const urlOnly = g.figures.filter((f) => !stored.includes(f));

    let sourceId: string | null = null;
    if (urlOnly.length > 0) {
      const existing = await db
        .select({ id: farmSources.id })
        .from(farmSources)
        .where(sql`${farmSources.sourceUrl} = ${g.sourceUrl} and ${farmSources.sha256} is null`)
        .limit(1);
      if (existing[0]) {
        sourceId = existing[0].id;
        await db
          .update(farmSources)
          .set({ kind: g.kind, title: g.title, publisher: g.title, updatedAt: new Date() })
          .where(eq(farmSources.id, sourceId));
      } else {
        const ins = await db
          .insert(farmSources)
          .values({ kind: g.kind, title: g.title, sourceUrl: g.sourceUrl, publisher: g.title, status: 'SOURCED', notes: 'Registered from the factor library; document not stored, publisher link only.' })
          .returning({ id: farmSources.id });
        sourceId = ins[0].id;
        sources++;
        console.log(`  add   ${g.title}`);
      }
    }

    for (const f of g.figures) {
      const target = stored.includes(f)
        ? (claimed.get(f.id) ?? claimed.get(f.id.split(':').slice(0, 2).join(':')) ?? sourceId)
        : sourceId;
      if (!target) continue;
      const found = await db.select({ id: farmSourceFigures.id }).from(farmSourceFigures).where(eq(farmSourceFigures.provenanceId, f.id)).limit(1);
      const row = {
        sourceId: target,
        provenanceId: f.id,
        label: f.source,
        locator: null as string | null,
        status: f.status,
        effectiveFrom: f.effectiveFrom,
        version: f.version,
        note: f.note ?? null,
      };
      if (found[0]) {
        await db.update(farmSourceFigures).set(row).where(eq(farmSourceFigures.id, found[0].id));
      } else {
        await db.insert(farmSourceFigures).values(row);
        figures++;
      }
    }
  }

  // 3. The reference register: URL-only rows, matched by URL else by title.
  const upsertReference = async (row: { kind: string; title: string; publisher: string; year: number | null; citation: string; sourceUrl: string | null; notes: string }) => {
    const existing = row.sourceUrl
      ? await db.select({ id: farmSources.id }).from(farmSources).where(sql`${farmSources.sourceUrl} = ${row.sourceUrl} and ${farmSources.sha256} is null`).limit(1)
      : await db.select({ id: farmSources.id }).from(farmSources).where(sql`${farmSources.title} = ${row.title} and ${farmSources.sha256} is null`).limit(1);
    if (existing[0]) {
      await db.update(farmSources).set({ kind: row.kind, title: row.title, publisher: row.publisher, year: row.year, citation: row.citation, sourceUrl: row.sourceUrl, notes: row.notes, updatedAt: new Date() }).where(eq(farmSources.id, existing[0].id));
    } else {
      await db.insert(farmSources).values({ kind: row.kind, title: row.title, publisher: row.publisher, year: row.year, citation: row.citation, sourceUrl: row.sourceUrl, status: 'SOURCED', notes: row.notes });
      sources++;
      console.log(`  add   ${row.title}`);
    }
  };
  for (const r of REFERENCE_SOURCES) {
    if (r.sourceUrl) namedUrls.add(r.sourceUrl);
    else namedTitles.add(r.title);
    await upsertReference({ kind: r.kind, title: r.title, publisher: r.publisher, year: r.year, citation: r.citation, sourceUrl: r.sourceUrl, notes: `Used for: ${r.usedFor} Registered from the reference register; document not stored, publisher link only.` });
  }

  // 4. Manufacturer spec sheets behind the equipment footprints.
  for (const sh of specSheetSources()) {
    namedUrls.add(sh.sourceUrl);
    await upsertReference({ kind: 'spec_sheet', title: sh.title, publisher: sh.publisher, year: null, citation: `Manufacturer specification sheet: ${sh.items.join('; ')}`, sourceUrl: sh.sourceUrl, notes: 'Used for: the plan footprint and clearances of the equipment line on the Facility page. Registered from the equipment library; document not stored, manufacturer link only.' });
  }

  // 5. Retire the seed's URL-only rows the code no longer names.
  const SEED_NOTE = /Registered from the (factor library|reference register|equipment library)/;
  const urlOnly = await db
    .select({ id: farmSources.id, title: farmSources.title, sourceUrl: farmSources.sourceUrl, notes: farmSources.notes })
    .from(farmSources)
    .where(sql`${farmSources.sha256} is null and ${farmSources.fileBytes} is null`);
  const stale = urlOnly.filter((r) => SEED_NOTE.test(r.notes ?? '') && !(r.sourceUrl ? namedUrls.has(r.sourceUrl) : namedTitles.has(r.title)));
  let retired = 0;
  for (const r of stale) {
    const linked = (await db.execute(sql`
      select
        (select count(*) from farm.sustainability_readings where source_id = ${r.id}) +
        (select count(*) from farm.refrigerant_service where source_id = ${r.id}) +
        (select count(*) from farm.period_bills where source_id = ${r.id}) +
        (select count(*) from farm.supplier_items where source_id = ${r.id}) +
        (select count(*) from farm.supplier_item_prices where source_id = ${r.id}) +
        (select count(*) from farm.supplier_lca_options where source_id = ${r.id}) as n`)).rows[0] as { n: number | string };
    if (Number(linked.n) > 0) {
      console.log(`  keep  ${r.title} (stale, but ${linked.n} record(s) link to it)`);
      continue;
    }
    await db.delete(farmSources).where(eq(farmSources.id, r.id));
    retired++;
    console.log(`  retire ${r.title}`);
  }

  console.log(`\nDone. ${sources} source(s) added, ${figures} figure(s) added, ${retired} stale source(s) retired; existing rows refreshed.`);
  await handle.close();
}

main().catch((e: unknown) => {
  console.error(e);
  process.exit(1);
});
